import { useEffect, useRef } from 'react'
import type { PanchayatForecast } from '../../types/api'
import { formatLongDate } from '../../lib/dates'
import { formatArea, formatElevation } from '../../lib/format'
import { VARIABLE_ORDER } from '../../lib/variables'
import { Logo } from '../brand/Logo'
import { Icon } from '../common/Icon'
import { InfoTip } from '../common/InfoTip'
import { AdvisoryActions } from './AdvisoryActions'
import { ConfidencePanel } from './ConfidencePanel'
import { VariableCard } from './VariableCard'

interface VillageDetailProps {
  village: PanchayatForecast
  district: string
  sourceLabel: string
  onBack: () => void
}

/**
 * What an officer reads before speaking to a village, in the order they need
 * it: what to do, then the weather behind it, then how far to trust it. The
 * uncertainty statement is always on screen and always printed.
 */
export function VillageDetail({ village, district, sourceLabel, onBack }: VillageDetailProps) {
  const headingRef = useRef<HTMLHeadingElement>(null)

  useEffect(() => {
    headingRef.current?.focus({ preventScroll: true })
  }, [village.panchayat_id])

  const variables = VARIABLE_ORDER.map((k) => village.variables[k]).filter(
    (v): v is NonNullable<typeof v> => v !== undefined,
  )
  const confidence = (village.variables.precip ?? variables[0])?.confidence
  const isGramPanchayat = village.unit_type === 'gram_panchayat'

  return (
    <article className="village print-area" aria-labelledby="village-title">
      <div className="print-only print-brand">
        <Logo tagline />
        <p>
          Village advisory · {village.block_name} block, {district} district ·{' '}
          {formatLongDate(village.date)} · {sourceLabel}
        </p>
      </div>

      <div className="village-bar no-print">
        <button type="button" className="back-link" onClick={onBack}>
          <Icon name="arrow-left" size={16} />
          All villages in {village.block_name}
        </button>
        <button type="button" className="btn btn-secondary btn-sm" onClick={() => window.print()}>
          <Icon name="print" size={16} />
          Print advisory
        </button>
      </div>

      <header className="panel-head">
        <p className="eyebrow">
          {isGramPanchayat ? (
            <span>Gram panchayat</span>
          ) : (
            <InfoTip label="Village cluster (approximate boundary)">
              Official gram-panchayat boundaries were not available for this area, so this unit
              groups about six neighbouring villages.
            </InfoTip>
          )}
        </p>
        <h2 id="village-title" className="panel-title" tabIndex={-1} ref={headingRef}>
          {village.panchayat_name}
        </h2>
        <p className="panel-sub num">
          <time dateTime={village.date}>{formatLongDate(village.date)}</time>
          <span className="dot-sep" aria-hidden>
            ·
          </span>
          {formatElevation(village.elevation_m)} elevation
          <span className="dot-sep" aria-hidden>
            ·
          </span>
          {formatArea(village.area_km2)}
        </p>
      </header>

      <section className="panel-section" aria-labelledby="v-advice">
        <h3 id="v-advice" className="section-title">
          What to tell farmers
        </h3>
        <p className="headline">{village.advisory.headline}</p>
        <AdvisoryActions items={village.advisory.items} />
      </section>

      <section className="panel-section" aria-labelledby="v-weather">
        <h3 id="v-weather" className="section-title">
          Weather for this village
        </h3>
        <p className="muted small band-key">
          <span>
            <span className="band-key-range" aria-hidden /> likely range (8 days in 10)
          </span>
          <span>
            <span className="band-key-dot" aria-hidden /> this village
          </span>
          <span>
            <span className="band-block-key" aria-hidden /> block forecast
          </span>
        </p>
        <div className="var-grid">
          {variables.map((v) => (
            <VariableCard key={v.variable} forecast={v} />
          ))}
        </div>
      </section>

      {confidence && (
        <section className="panel-section" aria-labelledby="v-conf">
          <h3 id="v-conf" className="section-title">
            How sure are we?
          </h3>
          <ConfidencePanel confidence={confidence} uncertainty={village.advisory.uncertainty_statement} />
        </section>
      )}

      <p className="print-only print-foot">
        Generated by FieldCast from the official block forecast. Village values are estimates, not
        measurements.
      </p>
    </article>
  )
}
